global:
  qsname: quickstart-chef-automate
  reporting: true
  regions:
    - ca-central-1
    - us-east-1
    - us-west-1
    - eu-west-1
    - eu-west-2
    - us-west-2
    - sa-east-1
    - eu-central-1
    - ap-northeast-1
    - ap-southeast-1
    - ap-southeast-2
    - ap-northeast-2

tests:
  qs_chefautomate1:
    template_file: chef-automate-master.template
    parameter_input: chef-automate-master.json
    regions:
      - ca-central-1
      - us-east-1
      - us-west-1
      - eu-central-1
      - eu-west-1
      - eu-west-2
      - us-west-2

